proposals/bulk-memory-operations/Overview.md
I think it's a better name than `set`, especially considering we may have a `table.set` in the future, which will likely set just one value.
It also follows naming of [Array.prototype.fill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill) which has similar behavior.
=> Rename `mem.set` to `mem.fill`

proposals/bulk-memory-operations/Overview.md
Using `memory.init` or `memory.drop` on an active segment is a validation error, not a trap.
=> Fix memory.{init,drop} mistakes in overview

document/core/binary/modules.rst, proposals/bulk-memory-operations/Overview.md
The current state seems to remove the placeholder table/memory index from the encoding to use it as an active flag.
This change proposes to keep the table/memory index by designating an index of -1 to mean "inactive segment", with 0+ indexing the module's memories/tables.
=> Tweak segment encoding to keep memory/table index

document/core/valid/instructions.rst, proposals/bulk-memory-operations/Overview.md
This is option 2a referenced here: https://github.com/WebAssembly/bulk-memory-operations/issues/27#issuecomment-421379736.
It allows segment indices that refer to active segments to pass validation, in anticipation of a future change to desugar active segments into init+drop instructions in the module's start function. That change implies that active segments will be dropped before any user code executes, and so will trap if referenced by a user init or drop instruction.
I've only changed the validation spec here, since the execution spec does not yet include this extension.
=> Validate segment index immediates regardless of passive-ness

proposals/bulk-memory-operations/Overview.md
I recently looked into adding support for bulk memory operations into
some Rust tooling in preparation for an overall threading story, and on
reading the overview here I was slightly confused about a few encodings
and some semantics. In the end I'm hopeful that these updates can help
clarify these for future readers! No major functional change is intended
here, only tweaks to wording and clarification of what I believe the
original intent of the instructions were.
Changes made were:
* Swapped out a broken `modules.html` link for a new link to the binary
encoding document.
* Clarified some wording about how the new encoding of data segments
with a flags field up front is backwards compatible.
* Lifted the style of specifying encodings in `BinaryEncoding.md` to
replace the current table for …
=> Clarify some encoding/semantics

proposals/bulk-memory-operations/Overview.md
This commit fixes #34 by specifying that the flags field (which
indicates if a segment is passive) is a `varuint32` instead of a
`uint8`. It was discovered in #34 that the memory index located at that
position today is a `varuint32`, which can be validly encoded as `0x80
0x00` in addition to `0x00` (in addition to a number of other
encodings). This means that if the first field were repurposed as a
single byte of flags, it would break these existing modules that work
today.
It's not currently known how many modules in the wild actually take
advantage of such an encoding, but it's probably better to be safe than
sorry!
Closes #34
=> Update binary encoding to use varuint32 for flags

proposals/bulk-memory-operations/Overview.md
Passive element segments now include an element type, and have a sequence of expressions instead of function indices.
=> Update Overview.md for element segments

proposals/bulk-memory-operations/Overview.md
Passive element segments now include an element type, and have a sequence of expressions instead of function indices.
=>  Update Overview.md for element segments

document/core/binary/instructions.rst
This would make it simpler to extend those instructions to support multiple memories/tables, and copying between different memories/tables.
The current encoding has a single placeholder zero byte for those instructions, which allows extension to multiple memories/tables, but would require a more complicated encoding to add two immediate indices.
=> Add a second placeholder zero to the encoding of `memory.copy` and `table.copy`.

proposals/bulk-memory-operations/Overview.md
See https://github.com/WebAssembly/reference-types/issues/18, #29, and #36
=> Two zero immediates for memory.copy and table.copy

proposals/bulk-memory-operations/Overview.md
The order of the `table.init` and `memory.init` immediates should be the index followed by the reserved byte (which is a placeholder for the table or memory index). This matches ordering of immediates in `call_indirect` (type index, followed by table index reserved byte).
=> Reverse order of {table,memory}.init immediates

proposals/bulk-memory-operations/Overview.md
`memory.init`, `memory.copy`, `memory.fill`, `table.init`, and `table.copy` should all fail if their ranges are out-of-bounds, even if the count is zero, similar to for active segments. See the discussions here: https://github.com/WebAssembly/design/issues/897, https://github.com/WebAssembly/bulk-memory-operations/issues/11.
=> Clarify *.{init,copy,fill} w/ zero count

proposals/bulk-memory-operations/Overview.md
These are clarifications of the trapping semantics for memory.fill, memory.init, and memory.copy, and thus also for table.init and table.copy.  We clarify that there's a low->high write order and under what circumstances partially written data are observed.
This needs to be further elaborated once we agree on #49, but shouldn't be controversial at the moment.
=> Clarify trapping semantics

interpreter/binary/decode.ml, interpreter/binary/encode.ml, interpreter/exec/eval.ml, interpreter/syntax/ast.ml, interpreter/syntax/operators.ml, interpreter/syntax/types.ml, interpreter/text/arrange.ml, interpreter/text/lexer.mll, interpreter/text/parser.mly, interpreter/valid/valid.ml
This adds the new operations, as well as the new data and element
segment formats.
Implemented:
* Text parsing/writing
* Binary encoding/decoding
* Validation
TODO:
* Tests
* DataCount section
* Proper encoding of passive element segments (using ref.null etc)
* Evaluation
=> [interpreter] Implement bulk memory operations

interpreter/binary/decode.ml, interpreter/binary/encode.ml, interpreter/exec/eval.ml, interpreter/syntax/ast.ml, interpreter/syntax/operators.ml, interpreter/syntax/types.ml, interpreter/text/arrange.ml, interpreter/text/parser.mly, interpreter/valid/valid.ml
I realised that it's simpler to just flatten segment_desc and segment into one type.
=> [interpreter] Flatten segment AST

interpreter/runtime/memory.ml, test/core/bulk.wast
Similar to the MVP, a 0-byte access at the end of the region is legal.
=> [Interpreter] Handle 0-byte copies properly.

interpreter/exec/eval.ml, interpreter/runtime/instance.ml, interpreter/runtime/memory.ml, interpreter/runtime/memory.mli, interpreter/runtime/table.ml, interpreter/runtime/table.mli, interpreter/text/arrange.ml, test/core/bulk.wast
`memory.init`, `data.drop`, `table.init`, `elem.drop`, `table.copy`
Also fix writing passive segments in the text format.
=> [Interpreter] Implement rest of the instructions

interpreter/binary/decode.ml, interpreter/binary/encode.ml, interpreter/exec/eval.ml, interpreter/syntax/ast.ml, interpreter/text/arrange.ml, interpreter/text/lexer.mll, interpreter/text/parser.mly, interpreter/valid/valid.ml, test/core/bulk.wast
It uses instruction encoding instead of assuming that each element is a
function variable:
```
0xd0 -> ref.null
0xd2 x -> ref.func x
```
=> [Interpreter] New syntax for passive elem segments

interpreter/binary/decode.ml, interpreter/binary/encode.ml, interpreter/exec/eval.ml, interpreter/runtime/memory.ml, interpreter/runtime/table.ml, interpreter/syntax/ast.ml, interpreter/text/arrange.ml, interpreter/text/parser.mly, interpreter/valid/valid.ml, test/core/bulk.wast
* The data count section is required if the `memory.init` or `data.drop`
instructions are used.
* `memory.init` had an off-by-one bug when reading at the end of a segment.
* All instructions that operate on regions need to compare length to 0
using unsigned comparison (e.g. `I32.gt_u n 0l`).
* Converting length from 32- to 64-bit now uses
`I64_convert.extend_i32_u`, instead of `Int64.of_int32`, since the
latter will sign-extend.
* The `table.copy` overlap test now uses an unsigned comparison.
* The passive element text syntax still allows function indexes, e.g.
`(elem passive $f1 $f2)`.
=> [Interpreter] Fix bugs found by Lars' tests

interpreter/binary/decode.ml, interpreter/binary/encode.ml, interpreter/exec/eval.ml, interpreter/runtime/instance.ml, interpreter/syntax/ast.ml, interpreter/text/arrange.ml, interpreter/text/parser.mly, interpreter/valid/valid.ml, test/core/binary.wast, test/core/bulk.wast, test/core/table_init.wast
* Move a segment's element type into a separate record field for passive segments (only), avoiding dummy appearances in active segments.
* Fix a minor bug in encoding condition for data count section, which caused one test to fail.
* Check all global decoding side conditions in the same place.
* Minor naming consolidation.
=> [interpreter] Refactor element type in passive segments

interpreter/binary/decode.ml, interpreter/binary/encode.ml, interpreter/syntax/ast.ml, interpreter/syntax/free.ml, interpreter/syntax/free.mli
Closer to a declarative spec. Symmetrically, enables to only encode data count section when needed.
(Btw, I noticed that the data count section is still missing in the spec.)
=> Replace decoding flag with predicate

document/core/binary/conventions.rst, document/core/binary/modules.rst, document/core/syntax/conventions.rst, document/core/syntax/modules.rst, document/core/text/conventions.rst, document/core/util/macros.def
This makes the side condition more generic by expressing it in terms of occurrences of data indices instead of specific instructions. It also simplifies slightly by using just one m.
=> [spec] Simplify datacount side condition

document/core/binary/modules.rst, document/core/syntax/modules.rst, document/core/util/macros.def, document/core/valid/modules.rst
The element segment binary format allows for `ref.null` as well as
`ref.func`.
TODO: text format
=> [spec] Proper binary format for element segments

document/core/exec/modules.rst, document/core/exec/runtime.rst, document/core/util/macros.def
This is copied and modified from this closed PR:
https://github.com/WebAssembly/bulk-memory-operations/pull/19
=> [spec] Runtime format of element and data segments

document/core/exec/instructions.rst, document/core/exec/runtime.rst
data.drop must update the store, not the frame. There may be multiple
copies of the frame, so any updates will only update once. We can make
sure that all copies are updated by using an indirection through data
addresses and updating the store instead.
See discussion in PR #92.
=> [spec] Use optional data instance, not data address

document/core/exec/conventions.rst, document/core/exec/instructions.rst, document/core/exec/runtime.rst, document/core/util/macros.def
This also adds `table.set` and `table.get` administrative instructions.
Only `table.set` is used for now, but `table.copy` will use both.
=> [spec] Add `table.init`, `elem.drop` exec text

proposals/bulk-memory-operations/Overview.md
It's only a trap if a byte is accessed out-of-bounds, not if the
destination or source index is out-of-bounds. This only makes a
difference when the length is zero, in which case the previous behavior
would trap, and the new behavior will be a no-op.
=> Update overview for the zero-byte OOB case

document/core/exec/instructions.rst, document/core/util/macros.def
Also fix some typos from previous CL (see macros.def)
=> [spec] Update text for zero-byte OOB case

document/core/exec/instructions.rst
This PR polishes the execution spec of `table.init`:
* Use `tab` as the name of the table, to be consistent with other instructions like `table.set`.
* Use more describing names for stack values: `dst`, `src`, and `cnt`, instead of `d`, `s`, `n`, respectively.
* Fix step numbering.
* Add return when `cnt = 0`.
* Add trap when `src` is out of bounds.
* Fix the call to `table.set`, i.e. push the `funcelem` on the stack, and call it with the correct immediate.
* In the formalism part:
* Change `cnt` to `(cnt+1)` in the trap case.
* Change the successor state in the not-trap cases from `S` to `S'`, as it is done for other instructions.
=> Polish table.init exec spec

document/core/binary/modules.rst
This PR implements the changes to the element segment encoding discussed in https://github.com/WebAssembly/bulk-memory-operations/issues/98.
I don't mention declared segments yet, because they don't exist in this proposal. I also don't mention
the externkind but immediately set it to 0x00, which is the value for external functions anyways.
=> Change element segment encoding

document/core/syntax/modules.rst, document/core/text/modules.rst, document/core/util/macros.def, document/core/valid/modules.rst, interpreter/binary/decode.ml, interpreter/binary/encode.ml, interpreter/exec/eval.ml, interpreter/syntax/ast.ml, interpreter/syntax/free.ml, interpreter/syntax/types.ml, interpreter/text/arrange.ml, interpreter/text/parser.mly, interpreter/valid/valid.ml, test/core/binary.wast, test/core/bulk.wast, test/core/elem.wast, test/core/imports.wast
This PR implements https://github.com/WebAssembly/bulk-memory-operations/issues/98:
* Extend the interpreter to handle the new element segment encoding;
* Add tests for the new element segment encoding;
* Adjust the text format specification;
The text format for case `0x1` needs the `func` keyword as a separator between a potential segment identifier and the function indices.
The text format needs a more verbose table index to distinguish between a potential segment identifier and the table index in case `0x2`. Alternatively we could just disallow table identifiers for active segments, since they are not useful anyways.
also-by: thibaudm@chromium.org
=> New element section encoding in the interpreter

document/core/appendix/index-rules.rst, document/core/binary/modules.rst, document/core/exec/instructions.rst, document/core/exec/modules.rst, document/core/exec/runtime.rst, document/core/syntax/modules.rst, document/core/syntax/types.rst, document/core/text/modules.rst, document/core/util/macros.def, document/core/valid/modules.rst, interpreter/binary/decode.ml, interpreter/binary/encode.ml, interpreter/exec/eval.ml, interpreter/runtime/table.ml, interpreter/syntax/ast.ml, interpreter/syntax/free.ml, interpreter/syntax/free.mli, interpreter/syntax/types.ml, interpreter/text/arrange.ml, interpreter/text/parser.mly, interpreter/valid/valid.ml
Refactor segment representation in AST (in both spec and interpreter) by separating out a `segment_mode`.
Other changes in Spec:
- Various fixes to text format grammar of segments.
- Factor out elemkind in binary format.
- Add note about possible future extension of element kinds.
- Add note about interpretation of segment kinds as bitfields.
- Fix some cross references.
Other changes in Interpreter:
- Rename {table,memory}_segment to {elem,data}_segment.
- Some rename elem to elem_expr and global.value to global.ginit for consistency with spec.
- Decode the elem segment kind as vu32 to maintain backwards compat.
- Some code simplifications / beautifications.
=> Segment refactoring

interpreter/exec/eval.ml, test/core/bulk.wast
In interpreter & test, table.init still trapped if segment has been dropped but length parameter was 0.
=> [interpreter/test] Update table.init semantics as well

test/core/memory_copy.wast, test/core/memory_fill.wast, test/core/memory_init.wast, test/core/table_copy.wast, test/core/table_init.wast, test/meta/generate_memory_copy.js, test/meta/generate_memory_fill.js, test/meta/generate_memory_init.js, test/meta/generate_table_copy.js, test/meta/generate_table_init.js
This is based on #126 and updates the generated tests.
=> [test] Update generated tests for OOBs and dropping changes

document/core/exec/instructions.rst, document/core/exec/runtime.rst, interpreter/exec/eval.ml, interpreter/runtime/instance.ml, proposals/bulk-memory-operations/Overview.md, test/core/bulk.wast, test/core/data.wast, test/core/elem.wast, test/core/memory_copy.wast, test/core/memory_fill.wast, test/core/memory_init.wast, test/core/table_copy.wast, test/core/table_init.wast, test/meta/generate_memory_copy.js, test/meta/generate_memory_fill.js, test/meta/generate_memory_init.js, test/meta/generate_table_copy.js, test/meta/generate_table_init.js
As discussed on #124, this introduces two simplifications, partially as a consequence of #111/#123:
1. Zero-length out-of-bound access trap again.
This reverts #100, #101, #102, which turn out to no longer be simplifications but rather complications in the presence of the OOB semantics more recently introduced by #111/#123.
2. Segment drops are treated like a shrink-to-zero.
This unifies drop check and OOB into a single check and avoids maintaining dropped as an extra state bit in the implementation. The only observable change in behaviour is that it is no longer a trap to (a) drop a segment twice, or (b) perform a 0-length init from a dropped segment at offset 0; both these cases are nops now.
Taken together, these changes also address #124.
Includes:
- Overview changes.
- Interpreter …
=> [interpreter] Simplify zero-len and drop semantics

proposals/bulk-memory-operations/Overview.md
Resolve TODOs and other outstanding issues; update the overview to the new encoding spec; add forward references to reference-types and multi-memory proposals where appropriate.
Pertains to #116.
=> New segment encoding

proposals/bulk-memory-operations/Overview.md
After the spec change in #126, byte copying order is not observable.
=> Delete mentions of copying order in Overview.md

test/core/bulk.wast, test/core/memory_init.wast, test/core/table_init.wast, test/meta/generate_memory_init.js, test/meta/generate_table_init.js
Decoding 64 as an signed LEB will produce the value -64 = 4294967232.
This change adds tests to ensure that the segment is decoded as 64.
=> Add test ensuring data segment index is unsigned

interpreter/valid/valid.ml, test/core/memory_init.wast, test/core/table_init.wast
The validation for `elem.drop` only checks that the referenced segment is valid within the context, it does not check the existence of tables. Therefore, when asserting that a module is invalid because of a bad segment index in `elem.drop`, we should expect an error message that references an unknown element segment, not a message that references an unknown table.
=> Fix expected validation errors for `elem.drop`

test/core/bulk.wast
This was fixed in the interpreter in the last PR, but only fixed the
messages in various assertions. This commit adds a new explicit test for
this.
=> Test that drop instructions work w/on memory/table

proposals/bulk-memory-operations/Overview.md
Fixes #142. A mismatched `DataCount` is malformed, not a validation error.
=> Change validation error -> malformed in Overview

document/core/binary/instructions.rst
The data/elem index comes before the memory/table index.
Fixes #146.
=> Fix {memory,table}.init immediate order

document/core/binary/modules.rst, document/core/text/modules.rst, interpreter/binary/decode.ml, interpreter/binary/encode.ml, interpreter/text/arrange.ml, interpreter/text/parser.mly, test/core/binary.wast, test/core/bulk.wast, test/core/elem.wast
Issue https://github.com/WebAssembly/reference-types/issues/69 requires
that `ref.null` instructions include a reference type immediate. This
concept isn't present in the bulk-memory proposal, but the encoding is
(in element segment expressions).
This change updates the binary and text format, but not the syntax. This
is OK for now, since the only reference type allowed here is `funcref`.
=> Update `ref.null` encoding after subtyping change

test/core/linking.wast
=> Test that partially out of bounds segments don't write to a memory/table

test/core/binary-leb128.wast
The encoding of the table index in binary-leb128.wast is incorrect with the bulk-memory extensions, see https://github.com/WebAssembly/bulk-memory-operations/issues/153. I saw and fixed the issue first in the reference types proposal (see https://github.com/WebAssembly/reference-types/pull/95), but apparently it also exists here.
=> [test] Fix table index encoding
